### ISSUE TITLE
Differentiate remote http-client endpoints

### ISSUE THREAD

**Issue by a-h** [DataDog/dd-trace-js#1022]
I created a new Serverless Framework project, with the datadog plugin installed.

```
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  datadog:
    addLayers: true
    logLevel: "info"
    flushMetricsToLogs: true
    site: datadoghq.eu
    enableXrayTracing: true
    enableDDTracing: true
    forwarder: arn:aws:lambda:eu-west-1:xxxxxxxxxxxxxxxx:function:dd-func-test-Forwarder-xxxxx
    enableTags: true
```

Then updated the function.

```
import { APIGatewayProxyHandler } from "aws-lambda";
import "source-map-support/register";
import fetch from "node-fetch";

export const hello: APIGatewayProxyHandler = async (event, _context) => {
  await fetch("https://jsonplaceholder.typicode.com/todos/1")
  try {
    await fetch("http://httpstat.us/500");
  } catch(e) {
    console.log("error calling httpstat.us", e);
  }
  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message:
          "Go Serverless Webpack (Typescript) v1.0! Your function executed successfully!",
        input: event,
      },
      null,
      2
    ),
  };
};
```

The code makes 2 HTTP requests, but when I look at the Service Map, I can only see one service (`http-client`).

<img width="1385" alt="Screen Shot 2020-07-09 at 11 20 28" src="https://user-images.githubusercontent.com/1029947/87028308-5adfcd00-c1d6-11ea-9e34-ee4e0a4c17e9.png">

One of them is returning 500 consistently (it's supposed to!), the other is working fine, and Datadog can differentiate on the hosts.

<img width="1511" alt="Screen Shot 2020-07-09 at 11 18 18" src="https://user-images.githubusercontent.com/1029947/87028104-06d4e880-c1d6-11ea-9c89-c753026a3acb.png">

It seems very clear that they're separate services. Is there a way to differentiate those `fetch` calls?

I'd expect each domain (i.e. jsonplaceholder.typicode.com, httpstat.us) to automatically be shown as a distinct service, and maybe have to manually distinguish where path segments are used to differentiate API calls. For example you might use https://api.example.com/service1 and https://api.example.com/service2 as prefixes.
