### ISSUE TITLE
Spans not appearing in the dashboard

### ISSUE THREAD

**Issue by fernandocamargoai** [DataDog/dd-trace-js#2546]
I have a nodejs app that is listening to a PubSub topic and then crawling pages according to the options passed in the message. Once I configured DataDog using `dd-trace-js`, I started seeing a lot of spans in the dashboard, mostly about the requests we do to crawl those pages. However, the main thing I wanted to trace was the function that runs for each message. I also want to add tags to it (like the URL and domain of the page). Since it doesn't get traced automatically, I tried to do it manually as follows:

```js
'use strict'

// Must come before importing any instrumented module.
import tracer from 'dd-trace';
tracer.init();

import { PubSub } from '@google-cloud/pubsub'


class QueueProcessor {
	constructor({projectId, topicNameOrId, subscriptionName}) {
		this.subscriptionName = subscriptionName
		this.topic = new PubSub({projectId}).topic(topicNameOrId)
		this.pageFetcher = new PageFetcher(this.bucket)
	}

	async run() {
		try {
			[this.subscription] = await this.topic.createSubscription(this.subscriptionName)
		} catch (error) {
			if (error.code == gRPCStatus.ALREADY_EXISTS || error.code == gRPCStatus.PERMISSION_DENIED) {
				this.subscription = this.topic.subscription(this.subscriptionName, {
					"flowControl": {
						"maxMessages": 3
					}
				})
			} else {
				throw error
			}
		}

		this.subscription.on('message', async (msg) => await this.processPubSubMessage(msg))
		this.subscription.on('error', async (err) => await this.processPubSubError(err))
	}

	async processPubSubError(err) {
		return await tracer.trace('QueueProcessor.processPubSubError', async () => {
			console.error('received error from pubsub:', err.toString())
			console.log('terminating')
			await this.subscription.close()
			await this.pageFetcher.close()
		})
	}

	async processPubSubMessage(message) {
		return await tracer.trace('QueueProcessor.processPubSubMessage', async (span, cb) => {
			let payload
			try {
				payload = JSON.parse(message.data)
				console.log(`received request, url:${payload.url}`)
				if (span !== null) {
					span.setTag("page_url", payload.url)
					span.setTag("page_domain", new URL(payload.url).hostname)
				}
				
				// Page Fetching specific stuff 
				
				if (response.ok()) {
					// Other stuff
					message.ack()
				} else {
					console.warn(`response wasn't OK, not acking`, response.status, response.toString)
					message.nack()
				}
				if (cb !== null) {
					cb()
				}
			} catch(e) {
				if (cb !== null) {
					cb(e)
				}
				if (e instanceof SupperssableError) {
					console.log(`got a suppressable error while fetching the page: ${e.toString()}\n\tpayload: ${payload}, won't retry`)
					message.ack()
				} else {
					console.warn(`failed to fetch page: ${e}\n\tpayload: ${payload}, will retry`)
					message.nack()
				}
			}
		})
	}
}

const processor = new QueueProcessor({
	projectId: values.google_cloud_project,
	topicNameOrId: values.pubsub_topic,
	subscriptionName: values.pubsub_subscription,
})
await processor.run()
```

I have this app deployed in Kubernetes with a DataDog Agent there. I mount the host `/var/run/datadog/` into the container and have the following `labels` and env variables:

```yaml
  labels:
    app.kubernetes.io/managed-by: pulumi
    tags.datadoghq.com/env: stg
    tags.datadoghq.com/service: page_change_detector
    tags.datadoghq.com/version: 0.0.1
```

```yaml
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
```

**Expected behaviour**
I expected to see one span for each message in the dashboard.

**Actual behaviour**
At first, I couldn't see any span there. But then, I got 2 spans there with error with a previous message of the code in which I didn't invoke the callback in case of success (in the end of the `try`). I thought maybe the problem was because I was invoking it, once I found out I should in the docs. I fixed the code but no luck. However, one more span appeared in the dashboard. The spans appearing there were quite random, it seems. I expected to see hundreds of spans there, instead I got only 3. Meanwhile, there are 1.6k spans for the `http.request` operation.

**Steps to reproduce**
The code provided above.

**Environment**

* **Operation system: Kubernetes 1.23.8-gke.1900**
* **Node.js version: 18.12.1**
* **Tracer version: 3.8.0**
* **Agent version: 7.38.0**
* **Relevant library versions: `"@google-cloud/pubsub": "^3.1.1"`**

package.json:
```json
{
  "name": "page-change-detector",
  "version": "0.0.1",
  "description": "Delta's worker to download contents of monitored pages and detect the changes",
  "main": "queue-processor.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "type": "module",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@google-cloud/pubsub": "^3.1.1",
    "@google-cloud/storage": "^6.5.2",
    "dd-trace": "^3.8.0",
    "form-data": "^4.0.0",
    "install": "^0.13.0",
    "npm": "^8.19.2",
    "puppeteer": "^19.0.0"
  }
}
```
