### ISSUE TITLE
Opensearch (v2.3) spans aren't collected

### ISSUE THREAD

**Issue by leonardbinet** [DataDog/dd-trace-js#2613]
**Expected behaviour**
I would expect to see Opensearch spans in my traces, and in APM services list.

**Actual behaviour**
I don't receive any span for requests to Opensearch.

<img width="651" alt="Screenshot 2022-12-14 at 11 49 00" src="https://user-images.githubusercontent.com/1590371/207578161-ef91f32c-c782-4833-9de7-87eee4b1f7ac.png">

Notes: 

- I'm sure that requests are actually made to that Opensearch cluster, here is an example of request where the client was ill-configured:
<img width="1769" alt="Screenshot 2022-12-14 at 11 48 40" src="https://user-images.githubusercontent.com/1590371/207578514-3102ddf3-5d80-45fb-92ba-2b126389c5b2.png">
<img width="1195" alt="Screenshot 2022-12-14 at 11 48 47" src="https://user-images.githubusercontent.com/1590371/207578520-b9104fcf-3f9c-4b59-a6fe-c18c3f8a4434.png">

- I initially used an Elasticsearch cluster in my application, and traces worked fine, this seems related to Opensearch specifically (version 2.3 in my case)
- traces neither work:
    - on local machine (macos)
    - on AWS EC2 instances (linux)

**Steps to reproduce**

`tracer.ts` file:
```
import tracer from 'dd-trace'

import { isTestEnvironment } from 'src/utils/environmentConf'

const APMEnabled = !isTestEnvironment()

if (APMEnabled) {
  tracer.init()
}
export default tracer
```

`docker-compose` file for local testing:
```
version: '3.8'

services:

  # Single node cluster
  opensearch:
    image: opensearchproject/opensearch:2.3.0
    environment:
      - cluster.name=opensearch-cluster-${COMPOSE_PROJECT_NAME}
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables security plugin
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - ${OPENSEARCH_PORT}:9200
    networks:
      - opensearch-net


networks:
  opensearch-net:

volumes:
  opensearch-data1:

```

**Environment**

* **Operation system:** Macos 13.0.1  (on Apple M1 Pro)
* **Node.js version:** v14.17.4
* **Tracer version:** 3.8.0 (opensearch support was introduced in [3.6.0](https://github.com/DataDog/dd-trace-js/releases/tag/v3.6.0))
* **Agent version:** Version: 7.40.1 on my local machine
* **Relevant library versions:**  `"@opensearch-project/opensearch": "^2.1.0",`

Relates to https://github.com/DataDog/dd-trace-js/pull/2348
