### ISSUE TITLE
Node Runtime Metrics missing Kubernetes tags

### ISSUE THREAD

**Issue by rarecrumb** [DataDog/dd-trace-js#2753]
**Expected behaviour**
APM traces and metrics should include tags from Kubernetes

**Actual behaviour**
No Kubernetes related tags are included

**Steps to reproduce**
Enable runtime metrics and inspect tags

**Environment**
Kubernetes

* **Operation system:**
* EKS / Kubernetes
* **Node.js version:**
* 18
* **Tracer version:**
* ^3.9.0
* **Agent version:**
* 7.41.1

Trying to use [Node Runtime Metrics](https://docs.datadoghq.com/tracing/metrics/runtime_metrics/nodejs) to track GC and Heap in a Kubernetes environment, but Kubernetes related tags like `pod_name` are missing from these metrics.

I've tried adding tags on the application pods using:

```yaml
        env:
            - name: DD_ENTITY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: DD_TAGS
              value: 'pod_name:%%metadata.name%%' # doesn't work
              value: 'pod_name:%%pod_name%%' # doesn't work
              value: 'pod_name:%%kube_pod_name%%' # doesn't work
```

I'd expect these Runtime Metrics to inherit tags from the agent or from the APM/dogstatsD config.

Not sure what to make of this: https://github.com/DataDog/dd-trace-js/blob/af8aeda767ce0521ef121dcde82c2fae3ce3ab16/packages/dd-trace/src/config.js#L78-L81
