### ISSUE TITLE
Blocklist for mongodb

### ISSUE THREAD

**Issue by lancedikson** [DataDog/dd-trace-js#831]
Hi, I get quite many requests from mongodb that I don't really want to be analyzed as they happen very often and can easily make it up to 1M of spans/month. I tried to find a way to block (filter out) particularly this kind of command but didn't find anything. 
![image](https://user-images.githubusercontent.com/1955931/72679058-3d963580-3ab4-11ea-8f7a-d6ae59bf2143.png)

Is there a way to have something similar to `http.blacklist` configuration option, but for commands to mongodb?

**Comment by EricZaporzan** [comment]
We had success setting this environment variable: 

`DD_APM_IGNORE_RESOURCES="ismaster admin\.\$cmd"`

That's on the Docker agent, but I suspect it'd work with other iterations as well.

**Comment by lancedikson** [comment]
Wow, thanks @EricZaporzan! It seems working for me, even though we're using DD on Heroku (without Docker) and there are no official docs about this env variable for Heroku agent. 

If somebody from the DD team reads this, it would be nice to have this env variable mentioned here: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/. Thanks.

**Comment by EricZaporzan** [comment]
Yes, documentation in this area could be a lot clearer. It seems like any of the variables enumerated in this file should be fair game for any of the iterations of the agent. https://github.com/DataDog/datadog-agent/blob/master/pkg/trace/config/env.go

Glad it worked!

**Comment by rochdev** [comment]
Glad you were able to get it to work! I'll leave the issue open since there would also be value to have this configuration directly in the tracer as well.

For the documentation, in general all environment variables are the same regardless of the how it's deployed. We should probably move the list to a single place instead of duplicating subsets.

**Comment by lancedikson** [comment]
Thanks, @rochdev 🙏 It would definitely help developers to find a way to filter out something redundant like those `ismaster admin.cmd` queries in my case.

**Comment by MartinLoeper** [comment]
These answers are money guys! Thanks so much! I think that many people like us using the MEAN stack are annoyed of these irrelevant spans showing up in APM.

**Comment by AndrejGajdos** [comment]
I tried this, but doesn't for me :/

**Comment by tedder** [comment]
in _my_ case, it wasn't working because I was putting `DD_APM_IGNORE_RESOURCES` on the application container. It needed to be on the collecting datadog agent container. I use helm (yaml), so the escaping is important:

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: monitoring
spec:
  chart:
    spec:
      chart: datadog
      version: "3.33.1"
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: monitoring
..
  values:
    agents:
      containers:
        traceAgent:
          env:
          - name: DD_APM_IGNORE_RESOURCES
            value: ismaster admin..cmd       # works, imprecise match
            value: ismaster admin.$cmd       # does NOT work
            value: "ismaster admin\.\$cmd"   # invalid YAML
            value: "ismaster admin\\.\\$cmd" # works
            value: 'ismaster admin\.\$cmd'   # works
..
```

Obviously, only use one of the `value` lines.
